import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    core: 'src/index.ts',
    stripe: 'src/stripe/index.ts',
    razorpay: 'src/razorpay/index.ts',
    react: 'src/react/index.ts',
    next: 'src/next/index.ts',
    adapters: 'src/adapters/index.ts',
    analytics: 'src/analytics/index.ts',
    'pricing-editor': 'src/pricing-editor/index.ts',
    webhooks: 'src/webhooks/index.ts',
    compliance: 'src/compliance/index.ts',
    globalization: 'src/globalization/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'next/server',
    'razorpay',
    'clsx',
    'tailwind-merge',
    'recharts',
    'lucide-react',
    'react-dnd',
    'react-dnd-html5-backend',
    'framer-motion',
  ],
  treeshake: true,
  minify: false,
});
